FROM node:22-alpine

ARG ENV_MODE
ENV ENV_MODE $ENV_MODE

ARG JWT_SECRET
ENV JWT_SECRET $JWT_SECRET

ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

ARG GRAPHQL_ENDPOINT
ENV GRAPHQL_ENDPOINT $GRAPHQL_ENDPOINT

ARG SUDO_PASSWORD
ENV SUDO_PASSWORD $SUDO_PASSWORD

ARG N8N_ENCRYPTION_KEY
ENV N8N_ENCRYPTION_KEY $N8N_ENCRYPTION_KEY

ARG NEXT_PUBLIC_TELEGRAM_BOT_NAME
ENV NEXT_PUBLIC_TELEGRAM_BOT_NAME $NEXT_PUBLIC_TELEGRAM_BOT_NAME

ARG NEXT_PUBLIC_DEBUG_WORLD3D
ENV NEXT_PUBLIC_DEBUG_WORLD3D $NEXT_PUBLIC_DEBUG_WORLD3D

ARG NEXT_PUBLIC_POSTS_ENABLED
ENV NEXT_PUBLIC_POSTS_ENABLED $NEXT_PUBLIC_POSTS_ENABLED

ARG NEXT_PUBLIC_WORLD3D_ENABLED
ENV NEXT_PUBLIC_WORLD3D_ENABLED $NEXT_PUBLIC_WORLD3D_ENABLED

ARG NEXT_PUBLIC_CRYPTO_ENABLED
ENV NEXT_PUBLIC_CRYPTO_ENABLED $NEXT_PUBLIC_CRYPTO_ENABLED

ARG NEXT_PUBLIC_SITE_TITLE
ENV NEXT_PUBLIC_SITE_TITLE $NEXT_PUBLIC_SITE_TITLE

ARG NEXT_PUBLIC_MAIN_PAGE_TITLE
ENV NEXT_PUBLIC_MAIN_PAGE_TITLE $NEXT_PUBLIC_MAIN_PAGE_TITLE


# ARG GRAPHQL_API_ENDPOINT
# ENV GRAPHQL_API_ENDPOINT $GRAPHQL_API_ENDPOINT

RUN apk update
RUN apk add curl

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

RUN npm run prisma:deploy
RUN npm run generate
RUN npm run prisma:seed

RUN if [ "$ENV_MODE" = "production" ] ; then yarn build ; fi

# Expose ports
EXPOSE 3000 4000
